### ISSUE TITLE
client login failed for {{<<"Can't pass  authentification">> }}

### ISSUE THREAD

**Issue by PowerDos** [emqx/emqx-auth-mongo#140]
### Environment
 - OS: alpine:3.8
 - EMQ:EMX3.0 v3.0.0
 - k8s: v1.13.1
### Description
> ConfigMap

```
apiVersion: v1
kind: ConfigMap
data:
  EMQX_CLUSTER__DISCOVERY: k8s
  EMQX_NAME: emqx
  EMQX_CLUSTER__K8S__APISERVER: https://kubernetes.default:443
  EMQX_CLUSTER__K8S__NAMESPACE: emqx
  EMQX_CLUSTER__K8S__SERVICE_NAME: emqx
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: ip
  EMQX_CLUSTER__K8S__APP_NAME: emqx
  EMQX_CLUSTER__NAME: emqxcl
  EMQX_CLUSTER__AUTOHEAL: 'on'
  EMQX_CLUSTER__AUTOCLEAN: 5m
  EMQX_ALLOW_ANONYMOUS: 'false'
  EMQX_ACL_NOMATCH: deny
  EMQX_LOADED_PLUGINS: 'emqx_auth_mongo,emqx_recon,emqx_retainer,emqx_dashboard,emqx_management'
  TZ: Asia/Shanghai
  EMQX_AUTH__MONGO__SERVER: '10.0.10.22:27017'
  EMQX_AUTH__MONGO__LOGIN: 'test'
  EMQX_AUTH__MONGO__PASSWORD: 'Hello123'
  EMQX_AUTH__MONGO__DATABASE: 'esy'
  EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: 'md5'
metadata:
  name: emqx-config
  namespace: emqx
```
> mongo

```
> db.auth('test', 'Hello123')
1
> db.mqtt_user.find({"username": "860001"});
{ "_id" : ObjectId("5b935e505eb9c25f7b59fd8d"), "username" : "860001", "password" : "4911b2c5bbe11eac60174e9780f24c62", "created" : ISODate("2018-09-08T05:29:52.743Z"), "is_superuser" : false, "__v" : 0 }
```
> error

```
2019-01-15 12:50:44.624 [error] mqttjs_59c1832335@10.244.1.0:38998 [MQTT] Username '860001' login failed for {{<<"Can't pass a
uthentification">>,                                                      
                                            [{mc_auth_logic,scram_sha_1_auth,
                                              5,              
                                              [{file,       
                                                "src/connection/mc_auth_logic.erl"},
                                               {line,55}]},               
                                             {mc_worker,auth_if_credentials,
                                              5,                 
                                              [{file,          
                                                "src/connection/mc_worker.erl"},
                                               {line,219}]},
                                             {mc_worker,init,1,
                                              [{file,
                                                "src/connection/mc_worker.erl"},
                                               {line,54}]},                      
                                             {proc_lib,init_p_do_apply,3,                                                    
                                              [{file,"proc_lib.erl"},                                                        
                                               {line,249}]}]},
                                           {gen_server,call,
                                            [<0.17564.28>,
                                             {query,<<"mqtt_user">>,false,
                                              false,true,false,false,0,-1,
                                              #{<<"username">> =>
                                                 <<"860001">>},
                                              #{}},
                                             infinity]}}
```

why i connect mqtt server with username: `860001` and password: `47045487`,  and server `Can't pass  authentification`

the ip address 10.0.10.22 is LAN address

Can u give me a hand? thank u~
